# Generated by Django 5.0 on 2024-04-05 12:59

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('brand', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('image', models.ImageField(upload_to='upload/car')),
                ('model', models.CharField(max_length=80)),
                ('condition', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=70, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('telegram', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YeneUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='upload/profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postedAt', models.DateTimeField(default=datetime.datetime.today)),
                ('status', models.BooleanField(default=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.yeneuser')),
            ],
        ),
    ]
