# Generated by Django 5.0 on 2024-04-05 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_car_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='yeneuser',
        ),
    ]
