# Generated by Django 5.0 on 2024-04-22 08:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_post_postedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimages',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='store.car'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postedAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 22, 11, 51, 0, 428974)),
        ),
    ]
