# Generated by Django 5.0 on 2024-04-22 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_carimages_car_alter_post_postedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='plate',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='postedAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 22, 15, 36, 59, 766445)),
        ),
    ]
