# Generated by Django 5.0 on 2024-04-23 02:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_car_plate_alter_post_postedat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postedAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 23, 5, 5, 14, 48036)),
        ),
        migrations.AlterField(
            model_name='yeneuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yeneuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
