# Generated by Django 5.0 on 2024-04-23 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_post_postedat_alter_yeneuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postedAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 23, 15, 5, 22, 730513)),
        ),
    ]
