# Generated by Django 5.0 on 2024-04-24 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_post_postedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postedAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 10, 21, 41, 231207)),
        ),
    ]
