# Generated by Django 5.0 on 2024-04-24 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_post_postedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postedAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 15, 11, 33, 327754)),
        ),
        migrations.AlterField(
            model_name='yeneuser',
            name='phone',
            field=models.CharField(default='0900000000', max_length=14),
        ),
        migrations.AlterField(
            model_name='yeneuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='upload/profile'),
        ),
    ]
