# Generated by Django 5.0 on 2024-04-24 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_post_postedat_alter_yeneuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postedAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 15, 55, 25, 206520)),
        ),
        migrations.AlterField(
            model_name='yeneuser',
            name='phone',
            field=models.CharField(blank=True, default='0900000000', max_length=14, null=True),
        ),
    ]
